### ISSUE TITLE
RuntimeError: The reset parameter is False but there is no n_features_in_ attribute. Is this estimator fitted?

### ISSUE THREAD

**Issue by menporulporiayalan** [abhishek374/dream11#32]
I Cloned this project and installed the required library. I tried running the script by `"python3 controller.py"` But I got the below error: 

```
preddatafeature updated with currently playing members
Calculation for best XI started
/usr/local/lib/python3.8/dist-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator StandardScaler from version 0.22.1 when using version 0.23.2. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(
Traceback (most recent call last):
  File "controller.py", line 213, in <module>
    execute_model_prediction(datapath, predictors, modelname, cat_cols, pred_col, usetimeseries=False, predpath=True)
  File "/home/emperoreby/sideprojects/dream11/main.py", line 110, in execute_model_prediction
    mod_predict.get_normalized_data()
  File "/home/emperoreby/sideprojects/dream11/point_prediction.py", line 248, in get_normalized_data
    master_numcols = self.enc[1].transform(master_numcols_df.values)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/preprocessing/_data.py", line 791, in transform
    X = self._validate_data(X, reset=False,
  File "/usr/local/lib/python3.8/dist-packages/sklearn/base.py", line 436, in _validate_data
    self._check_n_features(X, reset=reset)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/base.py", line 372, in _check_n_features
    raise RuntimeError(
RuntimeError: The reset parameter is False but there is no n_features_in_ attribute. Is this estimator fitted?
```

**Comment by madhavgoswami93** [comment]
Which python version are you using?
